function toSmallCapsName() {
    let myArray = {
        a: "\u1D43",
        b: "\u1D47",
        c: "\u1D9C",
        d: "\u1D48",
        e: "\u1D49",
        f: "\u1DA0",
        g: "\u1D4D",
        h: "\u02B0",
        i: "\u1DA6",
        j: "\u02B2",
        k: "\u1D4F",
        l: "\u02E1",
        m: "\u1D50",
        n: "\u207F",
        o: "\u1D52",
        p: "\u1D56",
        q: "\u146B",
        r: "\u02B3",
        s: "\u02E2",
        t: "\u1D57",
        u: "\u1D58",
        v: "\u1D5B",
        w: "\u02B7",
        x: "\u02E3",
        y: "\u02B8",
        z: "\u1DBB",
        0: "\u2070",
        1: "\u00B9",
        2: "\u00B2",
        3: "\u00B3",
        4: "\u2074",
        5: "\u2075",
        6: "\u2076",
        7: "\u2077",
        8: "\u2078",
        9: "\u2079",
        đ: "ᵈ",
        á: "ᵃ́",
        à: "ᵃ̀",
        ã: "ᵃ̃",
        ả: "ᵃ̉",
        ạ: "ᵃ̣",
        ă: "ᵃ̆",
        ắ: "ᵃ̆́",
        ằ: "ᵃ̆̀",
        ẵ: "ᵃ̆̃",
        ẳ: "ᵃ̆̉",
        ặ: "ᵃ̣̆",
        â: "ᵃ̂",
        ấ: "ᵃ̂́",
        ầ: "ᵃ̂̀",
        ẫ: "ᵃ̂̃",
        ẩ: "ᵃ̂̉",
        ậ: "ᵃ̣̂",
        é: "ᵉ́",
        è: "ᵉ̀",
        ẽ: "ᵉ̃",
        ẻ: "ᵉ̉",
        ẹ: "ᵉ̣",
        ê: "ᵉ̂",
        ế: "ᵉ̂́",
        ề: "ᵉ̂̀",
        ễ: "ᵉ̂̃",
        ể: "ᵉ̂̉",
        ệ: "ᵉ̣̂",
        i: "ⁱ",
        í: "ⁱ́",
        ì: "ⁱ̀",
        ĩ: "ⁱ̃",
        ỉ: "ⁱ̉",
        ị: "ⁱ̣",
        ó: "ᵒ́",
        ò: "ᵒ̀",
        õ: "ᵒ̃",
        ỏ: "ᵒ̉",
        ọ: "ᵒ̣",
        ố: "ᵒ̂́",
        ồ: "ᵒ̂̀",
        ỗ: "ᵒ̂̃",
        ổ: "ᵒ̂̉",
        ộ: "ᵒ̣̂",
        ô: "ᵒ̂",
        ớ: "ᵒ̛́",
        ờ: "ᵒ̛̀",
        ỡ: "ᵒ̛̃",
        ở: "ᵒ̛̉",
        ợ: "ᵒ̛̣",
        ơ: "ᵒ̛",
        ú: "ᵘ́",
        ù: "ᵘ̀",
        ũ: "ᵘ̃",
        ủ: "ᵘ̉",
        ụ: "ᵘ̣",
        ứ: "ᵘ̛́",
        ừ: "ᵘ̛̀",
        ữ: "ᵘ̛̃",
        ử: "ᵘ̛̉",
        ự: "ᵘ̛̣",
        ư: "ᵘ̛",
        ý: "ʸ́",
        ỳ: "ʸ̀",
        ỹ: "ʸ̃",
        ỷ: "ʸ̉",
        ỵ: "ʸ̣",
        A: "ᴬ",
        Á: "ᴬ́",
        À: "ᴬ̀",
        Ã: "ᴬ̃",
        Ả: "ᴬ̉",
        Ạ: "ᴬ̣",
        Ă: "ᴬ̆",
        Ắ: "ᴬ̆́",
        Ằ: "ᴬ̆̀",
        Ẵ: "ᴬ̆̃",
        Ẳ: "ᴬ̆̉",
        Ặ: "ᴬ̣̆",
        Â: "ᴬ̂",
        Ấ: "ᴬ̂́",
        Ầ: "ᴬ̂̀",
        Ẫ: "ᴬ̂̃",
        Ẩ: "ᴬ̂̉",
        Ậ: "ᴬ̣̂",
        E: "ᴱ",
        É: "ᴱ́",
        È: "ᴱ̀",
        Ẽ: "ᴱ̃",
        Ẻ: "ᴱ̉",
        Ẹ: "ᴱ̣",
        Ê: "ᴱ̂",
        Ế: "ᴱ̂́",
        Ề: "ᴱ̂̀",
        Ễ: "ᴱ̂̃",
        Ể: "ᴱ̂̉",
        Ệ: "ᴱ̣̂",
        I: "ᴵ",
        Í: "ᴵ́",
        Ì: "ᴵ̀",
        Ĩ: "ᴵ̃",
        Ỉ: "ᴵ̉",
        Ị: "ᴵ̣",
        O: "ᴼ",
        Ó: "ᴼ́",
        Ò: "ᴼ̀",
        Õ: "ᴼ̃",
        Ỏ: "ᴼ̉",
        Ọ: "ᴼ̣",
        Ô: "ᴼ̂",
        Ố: "ᴼ̂́",
        Ồ: "ᴼ̂̀",
        Ỗ: "ᴼ̂̃",
        Ổ: "ᴼ̂̉",
        Ộ: "ᴼ̣̂",
        Ơ: "ᴼ̛",
        Ớ: "ᴼ̛́",
        Ờ: "ᴼ̛̀",
        Ỡ: "ᴼ̛̃",
        Ở: "ᴼ̛̉",
        Ợ: "ᴼ̛̣",
        U: "ᵁ",
        Ú: "ᵁ́",
        Ù: "ᵁ̀",
        Ũ: "ᵁ̃",
        Ủ: "ᵁ̉",
        Ụ: "ᵁ̣",
        Ư: "ᵁ̛",
        Ứ: "ᵁ̛́",
        Ừ: "ᵁ̛̀",
        Ữ: "ᵁ̛̃",
        Ử: "ᵁ̛̉",
        Ự: "ᵁ̛̣",
        B: "ᴮ",
        C: "ᶜ",
        D: "ᴰ",
        Đ: "ᴰ",
        F: "ᶠ",
        G: "ᴳ",
        H: "ᴴ",
        J: "ᴶ",
        K: "ᴷ",
        L: "ᴸ",
        M: "ᴹ",
        N: "ᴺ",
        P: "ᴾ",
        Q: "ᑫ",
        R: "ᴿ",
        S: "ᔆ",
        T: "ᵀ",
        V: "ⱽ",
        W: "ᵂ",
        X: "ˣ",
        Z: "ᶻ",
        Ý: "ʸ́",
        Ỳ: "ʸ̀",
        Ỹ: "ʸ̃",
        Ỷ: "ʸ̉",
        Ỵ: "ʸ̣",
        Y: "ʸ"
    }
    let perfectName = splitName = "";
    let result = document.getElementById("result");
    let yourName = document.getElementById('yourName').value;
    result.innerHTML = "<div class=\"text-center\"><div class=\"spinner-border text-danger mx-auto d-block\" role=\"status\">\n</div>\Đang đổi tên, chờ xíu nhé...\n</div>";
    for (let i = 0; i < yourName.length; i++) {
        if (' \t\n\r\v'.indexOf(yourName[i]) > -1) {
            perfectName += yourName[i];
        } else {
            if (yourName[i] in myArray) {
                perfectName += myArray[yourName[i]];
            } else {
                perfectName = "Không hỗ trợ ký tự đặc biệt.";
                break;
            }
        }
        splitName += `<button class="btn btn-primary mr-1" type="button" onclick="replaceText('${myArray[yourName[i]]}');">${myArray[yourName[i]]}</button>`;
    }
    setTimeout(function() {
        result.innerHTML = `<div class="input-group mb-3">
        <input type="text" class="form-control" value="${perfectName}" aria-label="Small Caps Name" aria-describedby="button-copy">
        <div class="input-group-append">
            <button class="btn btn-primary" type="button" id="button-copy" onclick="copyToClipboardText(this);">Sao chép</button>
        </div>
    </div>`;
    }, 1500);
}

function copyToClipboardText(e) {
    copyToClipboard(e.parentElement.parentElement.children[0]), e.classList.add("btn-success"), e.innerHTML = "Đã chép"
}

function copyToClipboard(e) {
    let t;
    target = e, target.focus(), target.setSelectionRange(0, target.value.length);
    try {
        t = document.execCommand("copy")
    } catch (e) {
        t = !1
    }
    return t
}
